/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  examplesSidebar: [
    {type: 'autogenerated', dirName: 'examples'},
    /*,
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index', title: 'Examples',
        description: 'We have some examples',
        slug: '/doc/examples',
        keywords: ['examples'],
      } 
    }*/
  ],
  componentSidebar: [{type: 'autogenerated', dirName: 'components'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
